### ISSUE TITLE
Internal Review: AffiliateNFT.sol

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/referral-nfts#1]
[Will the owner be the deployer? Likely will be pDAO](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/AffiliateNFT.sol#L23)

[Reformat](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/AffiliateNFT.sol#L20)

[Reformat](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/AffiliateNFT.sol#L94)

[Views should go before mutative functions; generally, things are out of order regarding our standards](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/AffiliateNFT.sol#L62)
> see https://github.com/Kwenta/kwenta-solcurity

[Do not need to check that _recipient is not address(0) in _mint nor updateScore](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/996168f1f114645b01a1c2e6909c9d98ec451203/contracts/token/ERC721/ERC721.sol#L62)

[Not sure if checks for score != 0 are necessary in _mint and updateScore](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/AffiliateNFT.sol#L32)
> Why would we not allow scores being set to zero by the owner?

**Comment by 0xclem** [comment]
`Will the owner be the deployer? Likely will be pDAO`

Yeah it's probably worth passing the owner in the constructor.

`Reformat`

I need to have a look at your standards. I asked Jeremy to grant me access.

`Do not need to check that _recipient is not address(0) in _mint nor updateScore`

Good catch.

`Not sure if checks for score != 0 are necessary in _mint and updateScore`

IMO it is needed. There is no reason why the owner would create an affiliate NFT if the score is 0. Holding the NFT would just do nothing. Same for `updateScore` as they can just burn the token if they want the affiliate program with a specific holder to stop.

**Comment by JaredBorders** [comment]
I agree with: "Holding the NFT would just do nothing"

That is my point for removing the check. It is not deleterious behavior, so why should contracts waste gas preventing something harmless (if albeit useless)? But either way, logically, it is fine. just me nitpicking

**Comment by 0xclem** [comment]
Yeah ok I see your point now. You are right, we consume gas for nothing. I will remove it in the next iteration
