### ISSUE TITLE
Internal Review: BoostNFT.sol

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/referral-nfts#2]
[Will the owner be the deployer? Likely will be the pDAO](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/BoostNFT.sol#L39)

[Format issue](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/BoostNFT.sol#L36)

[This is technically not "state" bc it is immutable/constant (see lines 17-24)](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/BoostNFT.sol#L17)

[Can these be immutable? If so, all related setters can be removed](https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/src/BoostNFT.sol#L27)

_getTierFromReferralScore can be simplified (only two checks needed)
```
if (_score >= GOLD_SCORE) return GOLD_ID;
return _score >= SILVER_SCORE ? SILVER_ID : BRONZE_ID;
```

**Comment by 0xclem** [comment]
`Can these be immutable? If so, all related setters can be removed`

They could be. But I don't think they should. Reason is, if `stakingRewardsAddress` and `affiliateAddress` change, then BoostNFT will have to be redeployed too. This could be problematic if hundreds of traders hold these NFTs.

**Comment by JaredBorders** [comment]
`stakingRewardsAddress` should never change, given that it is upgradable. but I think it is reasonable to leave it mutable based on your point.
