### ISSUE TITLE
Internal Review: Tests

### ISSUE THREAD

**Issue by JaredBorders** [Kwenta/referral-nfts#3]
Not really necessary to fuzz test things like `onlyOwner` checks
https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/test/AffiliateNFT.t.sol#L129

nor when recipient is address(0)
https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/test/AffiliateNFT.t.sol#L136

There are a lot of fuzz tests that I didn't link that do this. Ultimately it is just not needed

**Comment by JaredBorders** [comment]
@tommyrharper @JChiaramonte7 @cmontecoding I do like how @0xclem separates tests within contracts
https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/test/BoostNFT.t.sol#L85

We should consider doing this in the future. Much cleaner

**Comment by 0xclem** [comment]
yeah fair. I tend to fuzz a lot to make sure it's bulletproof but some of the cases are probably overkill

**Comment by tommyrharper** [comment]
> @tommyrharper @JChiaramonte7 @cmontecoding I do like how @0xclem separates tests within contracts
> 
> https://github.com/Kwenta/referral-nfts/blob/83d0d993b0a37817f79674b93e0e69776a002d3b/test/BoostNFT.t.sol#L85
> 
> We should consider doing this in the future. Much cleaner

Yeah I quite like this pattern, I do a similar thing but with a different file for each contract, I think doing it this way though encourages breaking it up even more which is nice.

**Comment by tommyrharper** [comment]
> yeah fair. I tend to fuzz a lot to make sure it's bulletproof but some of the cases are probably overkill

Probably better to over fuzz than under fuzz I guess
